[package]
name = "proclock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proclock-macro = { path = "../proclock-macro" }
proclock-api = { path = "../proclock-api" }
