name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ '**' ]

jobs:
  clippy-and-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cargo Format Check
        run: cargo fmt --all -- --check
      - name: Cargo Clippy Check
        uses: actions-rs/clippy@master
        with:
          args: --all --all-targets --all-features -- --no-deps -D clippy::pedantic -D warnings
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Tests
        run: cargo test -- --show-output